### ISSUE TITLE
build and run in different versions?

### ISSUE THREAD

**Issue by BlinkyStitt** [buzzkillb/opera-docker#2]
Are you intentionally building on `golang:1.17.8-alpine3.15` but copying it into `golang:1.16.4-alpine3.13`? I think both should be `golang:1.17.8-alpine3.15`

**Comment by buzzkillb** [comment]
Looks like you are correct, need to update this anyways once go-opera is more finalized, plus changes to how snapshots are now done. But the basic docker-compose still should be okay.
